#PBS -N generate_25000_rows
#PBS -l select=1:ncpus=20:mem=62gb:ngpus=1:gpu_model=v100,walltime=24:00:00
#PBS -m abe
#PBS -M jmdanie@clemson.edu,cehrett@clemson.edu
#PBS -o job_data_gen_out.txt
#PBS -e job_data_gen_err.txt

source ~/.bashrc
conda activate nemo
cd ~/running_records/repetition_data_generation
python create_audio_training_data.py --input_file data/output_substitutions.csv --output_file data/sub_audio --num_samples 25000
rm data/sub_audio_* -f
