#PBS -N train_rep_model
#PBS -l select=1:ncpus=40:mem=62gb:ngpus=1:gpu_model=v100,walltime=72:00:00
#PBS -m abe
#PBS -M jmdanie@clemson.edu
#PBS -o rep_stdout1.txt
#PBS -e rep_stderr1.txt

source ~/.bashrc
cd ~/running_records/transformer_models
conda activate rr_env
python tune_TRK_for_BPE_with_trg_decoding_DEL.py -d ../repetition_data_generation/data/rep_audio.csv -m 10 -s witw/running_records/cycheugx -t RB2 RI2
